### ISSUE TITLE
[Feature Request] CMD+Q to quit the app

### ISSUE THREAD

**Issue by positlabs** [xanderfrangos/crushee#17]
I'd like to be able to quit the app with a keyboard shortcut. Currently it doesn't work with CMD+Q (on mac, at least)

**Comment by xanderfrangos** [comment]
Easy enough. I'll put that on my to-do list.

**Comment by positlabs** [comment]
I see it's in now, and I tested it. Works like a charm!
https://github.com/xanderfrangos/crushee/commit/e4ee67c4beb97b024a8ffdd97afed6ed1dae2222
