### ISSUE TITLE
[Question] What version of NodeJS is used to build the project?

### ISSUE THREAD

**Issue by positlabs** [xanderfrangos/crushee#19]
I'm not sure if it's an issue or not, but it would be nice to include the `engines` field in the package.json, just for consistency

https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines

**Comment by xanderfrangos** [comment]
At the moment, Crushee uses Electron 7, which targets Node 12. I'm going to bump that up next time I update Crushee, as Electron 7 is very out of date. I'll toss in the `engines` field when I do that. Thanks for the suggestion. 👍
