### ISSUE TITLE
going into a "Saving..." loop.. works otherwise.. great app!

### ISSUE THREAD

**Issue by vesper8** [xanderfrangos/crushee#2]
First of all.. it completely boggles my mind how this doesn't have thousands of stars!! omg not even 1!! I'm the first to star it?? Great friggin app! So easy to use and worked pretty much perfectly.. also great accompanying website!! This is a gem and it's such a shame it seems that no one knows about it!

One little hiccup.. this seems entirely superficial because the app worked perfectly... well ok two little hiccups

I tried it out on 8 images. Dragged them in.. first thing that puzzled me is that the initial crunch revealed that 6 out of 8 of the images were actually 200%+ larger!! So it actually made some of the images larger.. 2 of them it said were ~5% smaller

I had just run the 8 images through https://imageoptim.com.. maybe that had something to do with it

Ok, then I set up a width of 400.. hoping that it would save the ratio.. and it did! Wonderful. I clicked on "save all" and in the bottom left corner it started saying "Saving..." with a little spinner.

It did save them perfectly.. but it never got out of the "Saving..." loop.. still spinning even though it's done with its work

Like I said.. totally superficial bugs.. it worked perfectly! Will use again! And I'll tell whoever I can about it too! Great work! Thanks!!

**Comment by xanderfrangos** [comment]
Thanks for the star and feedback! 

I'm working on a rewrite of the app that will fix the infinite "Saving..." bug, along with a dozen of other bugs and UX quirks (like "optimizing" an image to 200% the file size). I'll definitely get the rewrite done faster now that I know I have a real user! 😄 

In the meantime, please feel free to report any other bugs or post suggestions.

**Comment by xanderfrangos** [comment]
The saving loop has been fixed along with plenty of other stuff in the 2.0 update. If you're still using the app, give it a try.

**Comment by vesper8** [comment]
sweet man! thanks for the heads up, just snatched it and will be using it again real soon! will let you know if I find anything but the changelog looks great!
