### ISSUE TITLE
Cannot find libjpeg or you have too old version (v6 or later required).

### ISSUE THREAD

**Issue by positlabs** [xanderfrangos/crushee#21]
I ran `npm install` but ran into an issue because of some incorrect path stuff. I had libjpeg installed, but it wasn't in the path.

```
Cannot find libjpeg or you have too old version (v6 or later required).
```

I added it to the path in .zprofile and `npm install` worked after that. If it's not installed, you can run `brew install jpeg` (on mac)

`eval $(/opt/homebrew/Cellar/jpeg/9d/bin shellenv)`

Might be worth adding a note to the build section in the readme

**Comment by positlabs** [comment]
Maybe this was a fluke. I can't get it to install now. Seems like others are having the same issue https://github.com/tjko/jpegoptim/issues/46

**Comment by xanderfrangos** [comment]
Hmm, you shouldn't need libjpeg installed. It should compile the library for you. Something must have changed with a dependency. I'll take a look at what's going on. I'm seeing the same error on my end (Mac only).

**Comment by positlabs** [comment]
FWIW I'm on an M1 mac so maybe it doesn't support this arch yet

**Comment by xanderfrangos** [comment]
@positlabs The latest code should be working now. I encountered the same issue on an Intel-based Mac and was able to get it working again. I'll be interested to hear if it runs OK on an M1 Mac as-is. Hopefully I can get proper ARM builds out at some point.

**Comment by positlabs** [comment]
Awesome! I'll check it out. The current mac installer works but most definitely running on Rosetta. Definitely worth looking into, but for now it's working just fine.

**Comment by positlabs** [comment]
Latest code works :)

**Comment by Stanzilla** [comment]
only blocker for arm builds right now is that the github actions worker for bigsur is in limited beta for now, otherwise very easy to set up!

**Comment by xanderfrangos** [comment]
@Stanzilla Good to know! I'm tempted to pick up a base model M1 Mac Mini, but I don't do enough with MacOS/iOS to justify it. 😅

**Comment by dmitry-brok** [comment]
Hello,

I ve'got the same issue on an x64 PC

_checking for jpeg_read_header in -ljpeg... no
Cannot find libjpeg or you have too old version (v6 or later required)._


 but I want to use either MozJPEG or libjpeg-turbo instead of libjpeg
How should I do this properly? 
Actually I built and installed mozjpeg (Ubuntu2210) but could not figure how to activate this option -DUSE_MOZJPEG=1

Thank you in advance
D.
