### ISSUE TITLE
Convert to WebP does not work

### ISSUE THREAD

**Issue by Stanzilla** [xanderfrangos/crushee#3]
I added a few pngs and checked "convert to webp" but the results were still png

**Comment by xanderfrangos** [comment]
Thanks for the bug report! 

Did you check the "Convert to WebP" option and then immediately save the files? The "save" button saves the results of the last round of crushing. So if you didn't check the WebP option prior to the last round of crushing, it wouldn't have applied. 

Try checking the WebP option, then pressing "re-crush", then "save". Let me know if that solves the problem.

I have an update coming in the next few days that should make it clearer if a file is being converted or not.

**Comment by Stanzilla** [comment]
Ohh that is a bit confusing but it works this way. thanks.
