### ISSUE TITLE
[Feature Request] Support percentage in resize options

### ISSUE THREAD

**Issue by Stanzilla** [xanderfrangos/crushee#4]
I would love to be able to downscale my images so being able to use percentage values in the height and width fields would be nice. Currently it does not complain if I put them there but it takes them as a pixel value.

**Comment by xanderfrangos** [comment]
Good idea! I'll include it in the next release.

**Comment by xanderfrangos** [comment]
This feature is now available in [v2.1.0](https://github.com/xanderfrangos/crushee/releases/tag/v2.1.0)

**Comment by Stanzilla** [comment]
awesome, thank you!
