### ISSUE TITLE
Doesn't respect image orientation

### ISSUE THREAD

**Issue by msbrunoalves** [xanderfrangos/crushee#56]
Hey, I've been using Crushee for a while but it has been giving me problems because it doesn't respect image orientation, it always transforms the image to horizontal.
[Here's an example](https://i.imgur.com/pvY2Zhf.png) of what Windows sees VS what Crushee sees.
Let me know if you need one of my pictures to reproduce the issue, it contains metadata so I might need to PM it to you.

**Comment by xanderfrangos** [comment]
I've noticed this as well, but it hasn't bothered me enough to fix it yet. 😅 I'll put this on my to-do list. Thanks for pointing it out.

**Comment by xanderfrangos** [comment]
Fixed as of v2.4.0! 👍
