### ISSUE TITLE
[Feature Request] JPEG conversion background color

### ISSUE THREAD

**Issue by positlabs** [xanderfrangos/crushee#73]
When converting to jpeg, it would be useful to be able to choose the background color. I commonly have white icons that need a black background, but the default is white, so I end up with a completely white image. Maybe it's too much of an edge case and it will clutter up the UI for everyone else, but I thought I'd mention it

**Comment by xanderfrangos** [comment]
@positlabs It took a while, but I finally got around to adding this. It's available in the Preferences window as of v2.4.2. 👍

**Comment by positlabs** [comment]
Awesome, thank you!!
