### ISSUE TITLE
Long File Name Prevent Image to Optimization and Resizing

### ISSUE THREAD

**Issue by ghost** [xanderfrangos/crushee#81]
Long File Name Prevent Image to Optimization and Resizing
![explorer_9f26f3YIl8](https://user-images.githubusercontent.com/32357822/176594212-fe83cd5f-1cd4-4bd2-98f6-d0467dfa5fed.png)

**Comment by ghost** [comment]
and if there any one image with long name, that you can't save other Optimization and Resizing images
stuck at saveing.....

![explorer_Eyxuy27nw3](https://user-images.githubusercontent.com/32357822/176599680-b591a1c0-51d2-4b8e-b0c5-e17ee9417dca.png)

**Comment by xanderfrangos** [comment]
@mindjek07 Yep, that's a bug. I can confirm on my end. I'll get that fixed. 👍

**Comment by ghost** [comment]
> @mindjek07 Yep, that's a bug. I can confirm on my end. I'll get that fixed. 👍

thanks

**Comment by xanderfrangos** [comment]
I've released [v2.4.1](https://github.com/xanderfrangos/crushee/releases/tag/v2.4.1), which should fix the issue. Let me know if you're encountering it.

**Comment by ghost** [comment]
So Fast, thanks for the update work smoothly :)
