### ISSUE TITLE
Process spawner leak

### ISSUE THREAD

**Issue by positlabs** [xanderfrangos/crushee#82]
I noticed my machine was running slowly even though I only had a few apps open. I opened the activity monitor to find a large number of crushee processes, despite having closed the app several hours prior. There were a lot more listed, but here are some examples: 
<img width="434" alt="Screen Shot 2022-07-05 at 5 19 57 PM" src="https://user-images.githubusercontent.com/1918844/177422922-33e4fd2e-06de-4053-bf20-0d5e3829edc0.png">

This was after I did the test for the french character files, so maybe it's related to that.

<img width="590" alt="Screen Shot 2022-07-05 at 5 54 56 PM" src="https://user-images.githubusercontent.com/1918844/177423149-204b817a-3af7-457f-a7bc-5fdfe0ae3b85.png">

**Comment by xanderfrangos** [comment]
Thanks for the bug report! That's definitely not good. I'll take a look and fix it as soon as I can.

**Comment by iib0011** [comment]
Hi @xanderfrangos. Does this project need new features? If yes I can be a maintainer

**Comment by xanderfrangos** [comment]
@positlabs I've released v2.4.4, which should fix it. I was able to replicate the issue on my Mac. One of the processes wouldn't quit when the app closed for some reason.

**Comment by positlabs** [comment]
Ah! I just responded to the wrong ticket :)
I'll give it a spin, thanks!

**Comment by positlabs** [comment]
It works! 🥳
